import Head from "next/head";
import Image from "next/image";
import test from "../public/sidebar/account-icon.svg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NFMJ-DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
    </div>
  );
}
