import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFMJ-DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
}
