import Head from "next/head";
import Image from "next/image";
import { Box, Select, Text } from "@chakra-ui/react";
import MainBar from "../components/MainBar";
import Wrapper from "../components/Wrapper";
import { TriangleDownIcon } from "@chakra-ui/icons";

import ManuscriptTable from "../components/ManuscriptTable";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NFMJ-DASHBOARD</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Wrapper>
        <Box mb="2.2rem">
          <Text fontWeight={600} fontSize="1.5rem">
            Dashboard
          </Text>
          <Text fontSize={"14px"} fontWeight={400}>
            Monday, May 20 2022
          </Text>
        </Box>

        <MainBar />

        <Box pt="1.3rem" w="100%" bg="#F7F6F9" mt="3rem" borderRadius={"12px"}>
          <Box
            pl="2rem"
            pr={"1.5rem"}
            display={"flex"}
            justifyContent="space-between"
            pb="1rem"
          >
            <Text fontWeight={500} fontSize="1.25rem">
              Manuscripts
            </Text>
            <Select
              icon={<TriangleDownIcon pl=".4rem" />}
              w="10rem"
              h="2.1rem"
              borderRadius="8px"
              focusBorderColor="none"
              bg="#E8EAF0"
              fontSize="14px"
              fontWeight={500}
              cursor="pointer"
            >
              <option value="all">All manuscripts</option>
              <option value="pending">Pending</option>
              <option value="accepted">Accepted</option>
            </Select>
          </Box>
          <ManuscriptTable maxH="20rem" />
        </Box>
      </Wrapper>
    </div>
  );
}
